<p><img alt="Colaboratory logo" height="45px" src="/img/colab_favicon.ico" align="left" hspace="10px" vspace="0px"></p>

<h1>Welcome to Colaboratory!</h1>


Colaboratory is a free Jupyter notebook environment that requires no setup and runs entirely in the cloud.

With Colaboratory you can write and execute code, save and share your analyses, and access powerful computing resources, all for free from your browser.

In [0]:
#@title Introducing Colaboratory { display-mode: "form" }
#@markdown This 3-minute video gives an overview of the key features of Colaboratory:
from IPython.display import YouTubeVideo
YouTubeVideo('inN8seMm7UI', width=600, height=400)

In [0]:
pip freeze


absl-py==0.9.0
alabaster==0.7.12
albumentations==0.1.12
altair==4.1.0
asgiref==3.2.7
astor==0.8.1
astropy==4.0.1.post1
astunparse==1.6.3
atari-py==0.2.6
atomicwrites==1.3.0
attrs==19.3.0
audioread==2.1.8
autograd==1.3
Babel==2.8.0
backcall==0.1.0
beautifulsoup4==4.6.3
bleach==3.1.4
blis==0.4.1
bokeh==1.4.0
boto3==1.12.35
botocore==1.15.35
Bottleneck==1.3.2
branca==0.4.0
bs4==0.0.1
CacheControl==0.12.6
cachetools==3.1.1
catalogue==1.0.0
certifi==2019.11.28
cffi==1.14.0
chainer==6.5.0
chardet==3.0.4
click==7.1.1
cloudpickle==1.3.0
cmake==3.12.0
cmdstanpy==0.4.0
colorlover==0.3.0
community==1.0.0b1
contextlib2==0.5.5
convertdate==2.2.0
coverage==3.7.1
coveralls==0.5
crcmod==1.7
cufflinks==0.17.3
cvxopt==1.2.4
cvxpy==1.0.29
cycler==0.10.0
cymem==2.0.3
Cython==0.29.16
daft==0.0.4
dask==2.12.0
dataclasses==0.7
datascience==0.10.6
decorator==4.4.2
defusedxml==0.6.0
descartes==1.1.0
dill==0.3.1.1
distributed==1.25.3
Django==3.0.5
dlib==19.18.0
docopt==0.6.2
docutils==0.15.2
dopamine-rl==1.0.5


In [0]:
pip install tensorboardX


     |████████████████████████████████| 204kB 2.6MB/s 


In [0]:
pip install ptan==0.6




SyntaxError: ignored

In [0]:
import gym

In [0]:
e = gym.make('CartPole-v0')


In [0]:
obs = e.reset()

In [0]:
obs


array([-0.04386192,  0.04499104,  0.02077762,  0.00169843])

In [0]:
e.action_space

Discrete(2)

In [0]:
e.observation_space

Box(4,)

In [0]:
e.step(0)

(array([-0.0429621 , -0.15042263,  0.02081159,  0.30086386]), 1.0, False, {})

In [0]:
e.action_space.sample()

1

In [0]:
e.action_space.sample()

0

In [0]:
e.observation_space.sample()

array([-4.9927956e-01, -1.7581361e+38, -2.6226875e-01,  9.9518036e+37],
      dtype=float32)

In [0]:
e.observation_space.sample()

array([-1.7115067e+00,  2.4846215e+38,  7.0303671e-02,  1.7825987e+38],
      dtype=float32)

In [3]:
import gym
if __name__ == "__main__":
    env = gym.make("CartPole-v0")
    total_reward = 0.0
    total_steps = 0
    obs = env.reset()
    while True:
        action = env.action_space.sample()
        obs, reward, done, _ = env.step(action)
        total_reward += reward
        total_steps += 1
        if done:
            break

print("Episode done  total reward %.2f" % (total_reward))

Episode done  total reward 12.00


In [4]:
a = torch.FloatTensor([2,3])

NameError: ignored

In [0]:
import torch

In [0]:
import numpy as np
a = torch.FloatTensor([2,3])

In [7]:
pip install torch

In [9]:
a

tensor([2., 3.])

In [10]:
a + 1

tensor([3., 4.])

In [0]:
a = torch.FloatTensor([2,3])

In [12]:
tensor([ 2., 3.])

NameError: ignored

In [13]:
a


tensor([2., 3.])

In [14]:
ca = a.to('cuda'); ca

RuntimeError: ignored

In [0]:
v1 = torch.tensor([1.0, 1.0], requires_grad=True)

In [0]:
v2 = torch.tensor([2.0, 2.0])

In [0]:
v_sum = v1 + v2

In [0]:
v_res = (v_sum*2).sum()

In [19]:
v_res

tensor(12., grad_fn=<SumBackward0>)

In [20]:
v1.is_leaf, v2.is_leaf

(True, True)